version: "3.9"

services:
  # --- Kafka KRaft controllers ---
  kafka-controller-1:
    image: apache/kafka:4.1.1
    container_name: kafka-controller-1
    command: >
      bash -c "
      /opt/kafka/bin/kafka-storage.sh format
        --config /etc/kafka/controller.properties
        --cluster-id=kraft-cluster-0001
        --ignore-formatted;
      /opt/kafka/bin/kafka-server-start.sh /etc/kafka/controller.properties
      "
    environment:
      KAFKA_LOG_DIRS: /var/lib/kafka
    volumes:
      - ./kafka/kraft/controller-1.properties:/etc/kafka/controller.properties
      - kafka-controller-1-data:/var/lib/kafka
    networks: [appnet]

  kafka-controller-2:
    image: apache/kafka:4.1.1
    container_name: kafka-controller-2
    command: >
      bash -c "
      /opt/kafka/bin/kafka-storage.sh format
        --config /etc/kafka/controller.properties
        --cluster-id=kraft-cluster-0001
        --ignore-formatted;
      /opt/kafka/bin/kafka-server-start.sh /etc/kafka/controller.properties
      "
    environment:
      KAFKA_LOG_DIRS: /var/lib/kafka
    volumes:
      - ./kafka/kraft/controller-2.properties:/etc/kafka/controller.properties
      - kafka-controller-2-data:/var/lib/kafka
    networks: [appnet]

  kafka-controller-3:
    image: apache/kafka:4.1.1
    container_name: kafka-controller-3
    command: >
      bash -c "
      /opt/kafka/bin/kafka-storage.sh format
        --config /etc/kafka/controller.properties
        --cluster-id=kraft-cluster-0001
        --ignore-formatted;
      /opt/kafka/bin/kafka-server-start.sh /etc/kafka/controller.properties
      "
    environment:
      KAFKA_LOG_DIRS: /var/lib/kafka
    volumes:
      - ./kafka/kraft/controller-3.properties:/etc/kafka/controller.properties
      - kafka-controller-3-data:/var/lib/kafka
    networks: [appnet]

  # --- Kafka KRaft brokers ---
  kafka-broker-1:
    image: apache/kafka:4.1.1
    container_name: kafka-broker-1
    depends_on: [kafka-controller-1, kafka-controller-2, kafka-controller-3]
    ports:
      - "19092:19092"
    command: >
      bash -c "
      /opt/kafka/bin/kafka-storage.sh format
        --config /etc/kafka/server.properties
        --cluster-id=kraft-cluster-0001
        --ignore-formatted;
      /opt/kafka/bin/kafka-server-start.sh /etc/kafka/server.properties
      "
    environment:
      KAFKA_LOG_DIRS: /var/lib/kafka
    volumes:
      - ./kafka/kraft/broker-1.properties:/etc/kafka/server.properties
      - kafka-broker-1-data:/var/lib/kafka
    networks: [appnet]

  kafka-broker-2:
    image: apache/kafka:4.1.1
    container_name: kafka-broker-2
    depends_on: [kafka-controller-1, kafka-controller-2, kafka-controller-3]
    ports:
      - "19093:19093"
    command: >
      bash -c "
      /opt/kafka/bin/kafka-storage.sh format
        --config /etc/kafka/server.properties
        --cluster-id=kraft-cluster-0001
        --ignore-formatted;
      /opt/kafka/bin/kafka-server-start.sh /etc/kafka/server.properties
      "
    environment:
      KAFKA_LOG_DIRS: /var/lib/kafka
    volumes:
      - ./kafka/kraft/broker-2.properties:/etc/kafka/server.properties
      - kafka-broker-2-data:/var/lib/kafka
    networks: [appnet]

  kafka-broker-3:
    image: apache/kafka:4.1.1
    container_name: kafka-broker-3
    depends_on: [kafka-controller-1, kafka-controller-2, kafka-controller-3]
    ports:
      - "19094:19094"
    command: >
      bash -c "
      /opt/kafka/bin/kafka-storage.sh format
        --config /etc/kafka/server.properties
        --cluster-id=kraft-cluster-0001
        --ignore-formatted;
      /opt/kafka/bin/kafka-server-start.sh /etc/kafka/server.properties
      "
    environment:
      KAFKA_LOG_DIRS: /var/lib/kafka
    volumes:
      - ./kafka/kraft/broker-3.properties:/etc/kafka/server.properties
      - kafka-broker-3-data:/var/lib/kafka
    networks: [appnet]

  # --- Schema Registry (Avro) ---
  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    container_name: schema-registry
    depends_on: [kafka-broker-1, kafka-broker-2, kafka-broker-3]
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-broker-1:9092,PLAINTEXT://kafka-broker-2:9093,PLAINTEXT://kafka-broker-3:9094
      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: BACKWARD
    ports:
      - "8081:8081"
    networks: [appnet]

  ##############################
  # Apicurio Registry (Avro)   #
  ##############################
  apicurio-registry:
    image: apicurio/apicurio-registry:latest-release
    container_name: apicurio-registry
    depends_on:
      - postgres
    ports:
      - "8082:8080"    # Apicurio runs on 8080 internally
    environment:
      - QUARKUS_HTTP_PORT=8080
      - APICURIO_STORAGE_KIND=sql
      - APICURIO_STORAGE_SQL_KIND=postgresql
      - APICURIO_DATASOURCE_URL=jdbc:postgresql://postgres/apicurio
      - APICURIO_DATASOURCE_USERNAME=apicurio
      - APICURIO_DATASOURCE_PASSWORD=secret
    networks: [ appnet ]

  # --- Kafka Connect (Debezium + sinks) ---
  kafka-connect:
    image: quay.io/debezium/connect:2.7
    container_name: kafka-connect
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
      - apicurio-registry
      - postgres
    environment:
      # Kafka cluster bootstrap
      BOOTSTRAP_SERVERS: kafka-broker-1:9092,kafka-broker-2:9093,kafka-broker-3:9094

      # Connect internal group & storage topics
      GROUP_ID: connect-cluster
      CONFIG_STORAGE_TOPIC: _connect-configs
      OFFSET_STORAGE_TOPIC: _connect-offsets
      STATUS_STORAGE_TOPIC: _connect-status

      # Enable Apicurio Avro converters
      ENABLE_APICURIO_CONVERTERS: "true"
      KEY_CONVERTER: io.apicurio.registry.utils.converter.AvroConverter
      VALUE_CONVERTER: io.apicurio.registry.utils.converter.AvroConverter
      KEY_CONVERTER_APICURIO_REGISTRY_URL: http://apicurio-registry:8080/apis/registry/v2
      VALUE_CONVERTER_APICURIO_REGISTRY_URL: http://apicurio-registry:8080/apis/registry/v2

      KEY_CONVERTER_APICURIO_REGISTRY_AUTO_REGISTER: "true"
      VALUE_CONVERTER_APICURIO_REGISTRY_AUTO_REGISTER: "true"

      KEY_CONVERTER_APICURIO_REGISTRY_FIND_LATEST: "true"
      VALUE_CONVERTER_APICURIO_REGISTRY_FIND_LATEST: "true"

      REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_ERRORS_LOG_ENABLE: true
      CONNECT_PLUGIN_PATH: /kafka/connect/plugins
    volumes:
      - ./connect-configs:/kafka/connect/connect-configs
      - ./plugins:/kafka/connect/plugins
    ports:
      - "8083:8083"
    networks: [appnet]

  # --- PostgreSQL ---
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appsecret
      POSTGRES_DB: musicdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: [appnet]

  # --- Elasticsearch (community single-node) ---
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks: [appnet]

  # --- OpenSearch (single-node) + Dashboards ---
  opensearch:
    image: opensearchproject/opensearch:2.14.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=MyStrongPass123!
    ports:
      - "9201:9200"
    networks: [appnet]

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.14.0
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
    ports:
      - "5601:5601"
    depends_on: [opensearch]
    networks: [appnet]

  # --- Spring Boot search API (JDK 25) ---
  catalog-service:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    container_name: catalog-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on: [elasticsearch, opensearch]
    ports:
      - "8080:8080"
    networks: [appnet]

networks:
  appnet: {}

volumes:
  kafka-controller-1-data: {}
  kafka-controller-2-data: {}
  kafka-controller-3-data: {}
  kafka-broker-1-data: {}
  kafka-broker-2-data: {}
  kafka-broker-3-data: {}
  postgres-data: {}
